spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data-ram-migration:
    channel:
      database:
        sparkConfig:
          fetchSize: 10000
          numPartitions: 20
          master: "local[8]"
        source:
          url: "jdbc:h2:~/source"
          user: sa
          password:
          driver: org.h2.Driver
          dbtable: test_source
          schema:
          columns:
            - PARENT_REFERENCE
            - ACCOUNTING_COMPANY
            - MUREX_EX_RATE
            - NDF_TYPE
            - EVENT_TYPE
            - EXCHANGE_RATE
            - EXCHANGE_RATE_LCY
            - OLD_BARRIER_RATE
            - OLD_STRIKE_PRICE
            - OLD_STRIKE_PRICE_2
            - OLD_UNDERLYING
            - OLD_UNDERLYING_DETAILS
            - OLD_QUANTITY
            - EXPIRED_QTY_NOTIONAL
            - ACCRUED_UNITS
            - CONTRACT_CCY
            - CONTRACT_CLASS
            - PUT_AMOUNT
            - PUT_CCY
            - CALL_AMOUNT
            - CALL_CCY
            - CAPITAL_INTEREST
            - PIVOT_PRICE
            - EURO_KNOCK_IN_LEVEL
            - EXOTIC_TYPE
            - UNDERLYING_DETAILS
            - UNDERLYING_SECURITY_ID
            - BARRIER_DETAILS
            - PORTFOLIO_NBR
            - PORTFOLIO_NBR_CREDIT
            - PORTFOLIO_NBR_DEBIT
            - ACCOUNT_NBR_CTPTY
            - ACCOUNT_NBR_CREDIT
            - ACCOUNT_NBR_DEBIT
            - ACCOUNT_NBR_FID
            - ACCOUNT_NBR_INTEREST_ON_LIQUIDATION
            - AMOUNT_SETTLEMENT_CCY
            - PURCHASE_AMOUNT
            - SALE_AMOUNT
            - PURCHASE_CCY_CODE
            - SALE_CCY_CODE
            - ASSET_CLASS
            - AVG_PURCHASE_PRICE
            - BROKERAGE_REVENUE
            - CURRENCY_CODE
            - FI_DESCRIPTION
            - FI_ID_JB
            - LOCATION_BC
            - MATURITY_DATE
            - NET_BROKERAGE_CHF
            - QUANTITY_NOMINAL
            - RATE
            - RUNNING_BALANCE
            - SECURITY_LONG_DESC
            - SETTLEMENT_CCY
            - TXN_DATE
            - TXN_ID
            - TXN_STATUS
            - TXN_DESC
            - TXN_FX_RATE
            - VALUE_DATE
            - MODIFIED_BY
            - MODIFIED_ON
            - UNIQUE_ID
            - IS_OUTGOING_FUND_TXN
            - TXN_REF_NBR
            - CUSTOMER_NBR
            - DC_FLAG
            - BOOKING_DATE
            - TXN_REF_NBR_TYPE
            - CONTRACT_REL_TXN
            - CONTRACT_SIZE
            - ORDER_REF_NBR
            - TXN_TYPE_CODE
            - UNDERLYING
            - IS_CORP_ACTION
            - AMOUNT_LOAN_DEPOSIT
            - AMOUNT_TOTAL
            - CTPTY_CURRENCY
            - AMOUNT_TOTAL_CTPTY_CCY
            - AMOUNT_TXN_CCY
            - CONTRACT_DATE
            - CONTRACT_NBR
            - POSITION_ID
            - POSITION_STATUS
            - POSITION_TYPE
            - TK
            - ISIN
            - COUNTERPARTY
            - INTEREST_CAP
            - AMOUNT_INTEREST
            - AMOUNT_NEW
            - NEW_RATE
            - VALUE_DATE_DEBIT
            - VALUE_DATE_CREDIT
            - ORDERER
            - ORDERER_BANK
            - PAYEE_NAME
            - PAYEE_BANK
            - RECEIVING_BANK
            - INTERMEDIARY_BANK
            - FOREIGN_BROKERAGE
            - FORWARD_RATE
            - LOCAL_BROKERAGE
            - SWISS_FEDERAL_STAMP_DUTY
            - CORRESPONDENT_FEES
            - THIRD_PARTY_FEES
            - STAMP_DUTY
            - GST
            - RATE_BASE
            - REALISED_PNL
            - MARGIN
            - MARKUP_VALUE
            - FEE_LOAN_DEPOSIT
            - CHARGE_LOAN_DEPOSIT
            - VAT_LOAN_DEPOSIT
            - FEE1_TRNSFR
            - FEE2_TRNSFR
            - CHARGES_TRNSFR
            - VAT_TRNSFR
            - FULL_TAX_PCT
            - AMOUNT_FULL_TAX
            - REDUCTION_PCT
            - AMOUNT_REDUCTION
            - REMAINING_PCT
            - REMAINING_UNITS
            - AMOUNT_REMAINING
            - FEE_CORP
            - FEE_CURRENCY_CODE
            - FEE_FX_RATE
            - CHARGE_CORP
            - OTHER_FEE_VAT
            - PACKAGE_REF
            - ISSUER_FEE
            - SETTLEMENT_ACCOUNT
            - SETTLEMENT_ACCOUNT_ID
            - BACK_OFFICE_REMARK
            - PAYEE_COMMUNICATION
            - INTER_BANK_COMMUNICATION
            - NEXT_COUPON_NBR
            - INTEREST_CAL_BASIS
            - STOCK_EXCHANGE
            - STOCK_EXCHANGE_CODE
            - TOTAL_INTEREST
            - ACCRUED_INTEREST
            - ACCURED_INTEREST_POS_CCY
            - ACTIVITY_CODE
            - ORDER_DATE
            - INTEREST_FREQ
            - EXPIRY_DATE
            - STRIKE_PRICE
            - TICKER_CODE
            - CLASSIFICATION_1
            - CLASSIFICATION_2
            - CLASSIFICATION_3
            - CLASSIFICATION_DESC1
            - CLASSIFICATION_DESC2
            - CLASSIFICATION_DESC3
            - REVERSAL_REF
            - EXTERNAL_REF
            - ASSET_TYPE
            - AUTH_DATETIME
            - OPERATOR_ID
            - CONTROL_USER_ID
            - T24_APPLN_PREFIX
            - SUB_ASSET_TYPE
            - SWAP_LEG
            - CATEGORY
            - CONTROL_T24_USER_ID
            - OPERATOR_T24_ID
            - OPTION_STYLE
            - FINANCIAL_TRANSACTIONS_TAX
            - SECURITY_TRANSFER_FEES
            - CUSTODIAN
            - INTEREST_DAYS
            - SETTLEMENT_DELIVERY_CODE
            - SPOT_RATE
            - COMPANY
            - REMARKS
            - TRADER_REMARKS
            - TRANS_UID
            - OPTION_TYPE
            - PRINCIPAL_CHANGE
            - PRODUCT_TYPE_SY
            - EARLY_MATURITY_DATE
            - EBV_FEES
            - BROKER_PRICE
            - SY_DX_REFERENCE
            - LEVERAGE
            - MIN_ACCRUED_PERIOD
            - STRIKE_PRICE_2
            - NOTIONAL_AMT
            - OLD_BARRIER_DETAILS
            - PREMIUM_CCY
            - PRICE_PT
            - PREMIUM_AMT
            - KNOCK_OUT_PRICE
            - DESCRIPTION
            - DIARY_ID
            - DX_CONTRACT_CODE
            - DX_OPEN_CLOSE
            - UNWIND_CHARGE_AMT
            - ADMIN_FEE
            - PENALTY_FEE
            - PE_CONTRIBUTION
            - PE_DISTRIBUTION
            - OPEN_CLEARED_BAL
            - OPEN_ACTUAL_BAL
            - ONLINE_ACTUAL_BAL
            - ONLINE_CLEARED_BAL
            - WORKING_BALANCE
            - OPEN_VAL_DATED_BAL
            - OPEN_AVAILABLE_BAL
            - SRC_MODIFIED_ON
            - ACTUAL_SETTLEMENT_DATE
            - BOOKING_TYPE
            - ADDITIONAL_DESC
            - BENEFICIARY_BANK
            - ASSET_GRP_TYPE
        target:
          url: "jdbc:h2:~/target"
          user: sa
          password:
          driver: org.h2.Driver
          dbtable: test_target
          schema:
          columns:
            - PARENT_REFERENCE_TRG
            - ACCOUNTING_COMPANY
            - MUREX_EX_RATE
            - NDF_TYPE
            - EVENT_TYPE
            - EXCHANGE_RATE
            - EXCHANGE_RATE_LCY
            - OLD_BARRIER_RATE
            - OLD_STRIKE_PRICE
            - OLD_STRIKE_PRICE_2
            - OLD_UNDERLYING
            - OLD_UNDERLYING_DETAILS
            - OLD_QUANTITY
            - EXPIRED_QTY_NOTIONAL
            - ACCRUED_UNITS
            - CONTRACT_CCY
            - CONTRACT_CLASS
            - PUT_AMOUNT
            - PUT_CCY
            - CALL_AMOUNT
            - CALL_CCY
            - CAPITAL_INTEREST
            - PIVOT_PRICE
            - EURO_KNOCK_IN_LEVEL
            - EXOTIC_TYPE
            - UNDERLYING_DETAILS
            - UNDERLYING_SECURITY_ID
            - BARRIER_DETAILS
            - PORTFOLIO_NBR
            - PORTFOLIO_NBR_CREDIT
            - PORTFOLIO_NBR_DEBIT
            - ACCOUNT_NBR_CTPTY
            - ACCOUNT_NBR_CREDIT
            - ACCOUNT_NBR_DEBIT
            - ACCOUNT_NBR_FID
            - ACCOUNT_NBR_INTEREST_ON_LIQUIDATION
            - AMOUNT_SETTLEMENT_CCY
            - PURCHASE_AMOUNT
            - SALE_AMOUNT
            - PURCHASE_CCY_CODE
            - SALE_CCY_CODE
            - ASSET_CLASS
            - AVG_PURCHASE_PRICE
            - BROKERAGE_REVENUE
            - CURRENCY_CODE
            - FI_DESCRIPTION
            - FI_ID_JB
            - LOCATION_BC
            - MATURITY_DATE
            - NET_BROKERAGE_CHF
            - QUANTITY_NOMINAL
            - RATE
            - RUNNING_BALANCE
            - SECURITY_LONG_DESC
            - SETTLEMENT_CCY
            - TXN_DATE
            - TXN_ID
            - TXN_STATUS
            - TXN_DESC
            - TXN_FX_RATE
            - VALUE_DATE
            - MODIFIED_BY
            - MODIFIED_ON
            - UNIQUE_ID
            - IS_OUTGOING_FUND_TXN
            - TXN_REF_NBR
            - CUSTOMER_NBR
            - DC_FLAG
            - BOOKING_DATE
            - TXN_REF_NBR_TYPE
            - CONTRACT_REL_TXN
            - CONTRACT_SIZE
            - ORDER_REF_NBR
            - TXN_TYPE_CODE
            - UNDERLYING
            - IS_CORP_ACTION
            - AMOUNT_LOAN_DEPOSIT
            - AMOUNT_TOTAL
            - CTPTY_CURRENCY
            - AMOUNT_TOTAL_CTPTY_CCY
            - AMOUNT_TXN_CCY
            - CONTRACT_DATE
            - CONTRACT_NBR
            - POSITION_ID
            - POSITION_STATUS
            - POSITION_TYPE
            - TK
            - ISIN
            - COUNTERPARTY
            - INTEREST_CAP
            - AMOUNT_INTEREST
            - AMOUNT_NEW
            - NEW_RATE
            - VALUE_DATE_DEBIT
            - VALUE_DATE_CREDIT
            - ORDERER
            - ORDERER_BANK
            - PAYEE_NAME
            - PAYEE_BANK
            - RECEIVING_BANK
            - INTERMEDIARY_BANK
            - FOREIGN_BROKERAGE
            - FORWARD_RATE
            - LOCAL_BROKERAGE
            - SWISS_FEDERAL_STAMP_DUTY
            - CORRESPONDENT_FEES
            - THIRD_PARTY_FEES
            - STAMP_DUTY
            - GST
            - RATE_BASE
            - REALISED_PNL
            - MARGIN
            - MARKUP_VALUE
            - FEE_LOAN_DEPOSIT
            - CHARGE_LOAN_DEPOSIT
            - VAT_LOAN_DEPOSIT
            - FEE1_TRNSFR
            - FEE2_TRNSFR
            - CHARGES_TRNSFR
            - VAT_TRNSFR
            - FULL_TAX_PCT
            - AMOUNT_FULL_TAX
            - REDUCTION_PCT
            - AMOUNT_REDUCTION
            - REMAINING_PCT
            - REMAINING_UNITS
            - AMOUNT_REMAINING
            - FEE_CORP
            - FEE_CURRENCY_CODE
            - FEE_FX_RATE
            - CHARGE_CORP
            - OTHER_FEE_VAT
            - PACKAGE_REF
            - ISSUER_FEE
            - SETTLEMENT_ACCOUNT
            - SETTLEMENT_ACCOUNT_ID
            - BACK_OFFICE_REMARK
            - PAYEE_COMMUNICATION
            - INTER_BANK_COMMUNICATION
            - NEXT_COUPON_NBR
            - INTEREST_CAL_BASIS
            - STOCK_EXCHANGE
            - STOCK_EXCHANGE_CODE
            - TOTAL_INTEREST
            - ACCRUED_INTEREST
            - ACCURED_INTEREST_POS_CCY
            - ACTIVITY_CODE
            - ORDER_DATE
            - INTEREST_FREQ
            - EXPIRY_DATE
            - STRIKE_PRICE
            - TICKER_CODE
            - CLASSIFICATION_1
            - CLASSIFICATION_2
            - CLASSIFICATION_3
            - CLASSIFICATION_DESC1
            - CLASSIFICATION_DESC2
            - CLASSIFICATION_DESC3
            - REVERSAL_REF
            - EXTERNAL_REF
            - ASSET_TYPE
            - AUTH_DATETIME
            - OPERATOR_ID
            - CONTROL_USER_ID
            - T24_APPLN_PREFIX
            - SUB_ASSET_TYPE
            - SWAP_LEG
            - CATEGORY
            - CONTROL_T24_USER_ID
            - OPERATOR_T24_ID
            - OPTION_STYLE
            - FINANCIAL_TRANSACTIONS_TAX
            - SECURITY_TRANSFER_FEES
            - CUSTODIAN
            - INTEREST_DAYS
            - SETTLEMENT_DELIVERY_CODE
            - SPOT_RATE
            - COMPANY
            - REMARKS
            - TRADER_REMARKS
            - TRANS_UID
            - OPTION_TYPE
            - PRINCIPAL_CHANGE
            - PRODUCT_TYPE_SY
            - EARLY_MATURITY_DATE
            - EBV_FEES
            - BROKER_PRICE
            - SY_DX_REFERENCE
            - LEVERAGE
            - MIN_ACCRUED_PERIOD
            - STRIKE_PRICE_2
            - NOTIONAL_AMT
            - OLD_BARRIER_DETAILS
            - PREMIUM_CCY
            - PRICE_PT
            - PREMIUM_AMT
            - KNOCK_OUT_PRICE
            - DESCRIPTION
            - DIARY_ID
            - DX_CONTRACT_CODE
            - DX_OPEN_CLOSE
            - UNWIND_CHARGE_AMT
            - ADMIN_FEE
            - PENALTY_FEE
            - PE_CONTRIBUTION
            - PE_DISTRIBUTION
            - OPEN_CLEARED_BAL
            - OPEN_ACTUAL_BAL
            - ONLINE_ACTUAL_BAL
            - ONLINE_CLEARED_BAL
            - WORKING_BALANCE
            - OPEN_VAL_DATED_BAL
            - OPEN_AVAILABLE_BAL
            - SRC_MODIFIED_ON
            - ACTUAL_SETTLEMENT_DATE
            - BOOKING_TYPE
            - ADDITIONAL_DESC
            - BENEFICIARY_BANK
            - ASSET_GRP_TYPE


