spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data-ram-migration:
    channel:
      save:
        format: CSV
      batch-process:
        batchSize: 100
        recordsPerBatch: 10000
      database:
        sparkConfig:
          fetchSize: 500
          numPartitions: 20
          master: "local[*]"
        source:
          url: "jdbc:h2:~/source"
          user: sa
          password:
          driver: org.h2.Driver
          dbtable: source_emp
          schema:
          columns:
            - emp_id
            - emp_name
            - sal
        target:
          url: "jdbc:h2:~/target"
          user: sa
          password:
          driver: org.h2.Driver
          dbtable: target_emp
          schema:
          columns:
            - emp_id
            - emp_name
            - salary


